server:
  #端口
  port: 8088
spring:
  rabbitmq:
    host: 192.168.30.166
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-confirms: true #开启发送确认
    publisher-returns: true #开启发送失败退回
    listener:
      simple:
        acknowledge-mode: manual #ack manual
  #redis配置

  # 数据源配置
  datasource:
    url: jdbc:mysql://192.168.30.13:3306/portal_ms?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
#日志
logging:
  config: classpath:log/logback.xml
  path: /ad/bin/back/portal-ms/log/

#自定义配置属性
#源码生成文件夹
source-code-dic:  D:\output\portal-ms\dic
source-code-zipfile:  D:\output\portal-ms\源码.rar

#搜索文件生成包的位置
#本地路径
lucence-dic: /ad/bin/back/portal-ms/lucence

#忽略验证码登录
ignore-login-code: true

#Redis中session用户权限列表是否加密
permissions-encryted: false

#adms报表任务访问根地址
adms.reportJob.url: http://adms.e-ports-ms.com:8080/reportJob/count

#上传文件至filestorage
local-upload-filestorage: http://192.168.30.166:10236/filestorage/uploadFilesAndSave