server:
  #端口
  port: 4567
spring:
  rabbitmq:
    host: 39.104.124.39
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-confirms: true #开启发送确认
    publisher-returns: true #开启发送失败退回
    listener:
      simple:
        acknowledge-mode: manual #ack manual
  # 数据源配置
  datasource:
    url: jdbc:sqlite::resource:db/shop.db
    username:
    password:
    driver-class-name: org.sqlite.JDBC

#日志
logging:
  config: classpath:log/logback.xml
  path: D:\output\portal-ms\log\


#忽略验证码登录
ignore-login-code: true

#Redis中session用户权限列表是否加密
permissions-encryted: false


#上传文件至filestorage
local-upload-filestorage: http://192.168.30.98:10236/filestorage/uploadFilesAndSave
